_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 256
compile:
    value: false
dataset:
    value: pile
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
enable_spectral_analysis:
    value: true
eval_interval:
    value: 100
eval_iters:
    value: 50
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.0005
log_interval:
    value: 10
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 5e-05
n_embd:
    value: 256
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out-spectral
save_interval:
    value: 200
spectral_analysis_interval:
    value: 200
wandb_log:
    value: true
wandb_project:
    value: shakespeare_spectral
wandb_run_name:
    value: nanogpt-shakespeare-spectral
warmup_iters:
    value: 200
weight_decay:
    value: 0.1
